### ISSUE TITLE
Example source for improving memmove

### ISSUE THREAD

**Issue by phillipjohnston** [esmil/musl#1]
Hi,

I was reviewing some of your functions, and I noticed that you use a modulo in memmove.  This is a pretty expensive operation computationally, and seems like this could be dramatically improved using bitwise operations to check alignment.  Here's an example:

https://opensource.apple.com/source/ntp/ntp-13/ntp/libntp/memmove.c

I hope this suggestion helps!  Have a wonderful day.

**Comment by esmil** [comment]
Hey, this is not the official musl repo at all. It's just a place for me to store two patches I had to musl a few years ago. This is the official repo:
http://git.musl-libc.org/cgit/musl/tree

**Comment by phillipjohnston** [comment]
Sorry about that!
